import '../models/daily_phrase.dart';
import '../utils/app_icons.dart';

/// Built-in phrase packs inspired by MandaLearn's theme system.
const List<PhraseCategory> kPhraseCategories = [
  PhraseCategory(
    id: 'greetings',
    iconPath: AppIcons.wave,
    nameZh: '打招呼',
    nameEn: 'Greetings',
    phrases: [
      DailyPhrase(chinese: '你好', pinyin: 'nǐ hǎo', english: 'Hello'),
      DailyPhrase(chinese: '早上好', pinyin: 'zǎo shang hǎo', english: 'Good morning'),
      DailyPhrase(chinese: '晚上好', pinyin: 'wǎn shang hǎo', english: 'Good evening'),
      DailyPhrase(chinese: '再見', pinyin: 'zài jiàn', english: 'Goodbye'),
      DailyPhrase(chinese: '謝謝', pinyin: 'xiè xie', english: 'Thank you'),
      DailyPhrase(chinese: '不客氣', pinyin: 'bú kè qi', english: "You're welcome"),
      DailyPhrase(chinese: '對不起', pinyin: 'duì bu qǐ', english: 'Sorry'),
      DailyPhrase(chinese: '沒關係', pinyin: 'méi guān xi', english: "It's okay"),
    ],
  ),
  PhraseCategory(
    id: 'restaurant',
    iconPath: AppIcons.burger,
    nameZh: '餐廳與美食',
    nameEn: 'Restaurant',
    phrases: [
      DailyPhrase(chinese: '筷子', pinyin: 'kuài zi', english: 'Chopsticks'),
      DailyPhrase(chinese: '點菜', pinyin: 'diǎn cài', english: 'Order food'),
      DailyPhrase(chinese: '買單', pinyin: 'mǎi dān', english: 'Pay the bill'),
      DailyPhrase(chinese: '服務員', pinyin: 'fú wù yuán', english: 'Waiter'),
      DailyPhrase(chinese: '菜單', pinyin: 'cài dān', english: 'Menu'),
      DailyPhrase(chinese: '好吃', pinyin: 'hǎo chī', english: 'Delicious'),
      DailyPhrase(chinese: '米飯', pinyin: 'mǐ fàn', english: 'Rice'),
      DailyPhrase(chinese: '飲料', pinyin: 'yǐn liào', english: 'Drink'),
    ],
  ),
  PhraseCategory(
    id: 'school',
    iconPath: AppIcons.school,
    nameZh: '校園生活',
    nameEn: 'School Life',
    phrases: [
      DailyPhrase(chinese: '課本', pinyin: 'kè běn', english: 'Textbook'),
      DailyPhrase(chinese: '操場', pinyin: 'cāo chǎng', english: 'Playground'),
      DailyPhrase(chinese: '考試', pinyin: 'kǎo shì', english: 'Exam'),
      DailyPhrase(chinese: '同學', pinyin: 'tóng xué', english: 'Classmate'),
      DailyPhrase(chinese: '老師', pinyin: 'lǎo shī', english: 'Teacher'),
      DailyPhrase(chinese: '作業', pinyin: 'zuò yè', english: 'Homework'),
      DailyPhrase(chinese: '教室', pinyin: 'jiào shì', english: 'Classroom'),
      DailyPhrase(chinese: '圖書館', pinyin: 'tú shū guǎn', english: 'Library'),
    ],
  ),
  PhraseCategory(
    id: 'shopping',
    iconPath: AppIcons.cart,
    nameZh: '超市購物',
    nameEn: 'Shopping',
    phrases: [
      DailyPhrase(chinese: '收銀台', pinyin: 'shōu yín tái', english: 'Cashier'),
      DailyPhrase(chinese: '打折', pinyin: 'dǎ zhé', english: 'Discount'),
      DailyPhrase(chinese: '購物車', pinyin: 'gòu wù chē', english: 'Shopping cart'),
      DailyPhrase(chinese: '零食', pinyin: 'líng shí', english: 'Snacks'),
      DailyPhrase(chinese: '多少錢', pinyin: 'duō shao qián', english: 'How much?'),
      DailyPhrase(chinese: '太貴了', pinyin: 'tài guì le', english: 'Too expensive'),
      DailyPhrase(chinese: '便宜', pinyin: 'pián yi', english: 'Cheap'),
      DailyPhrase(chinese: '找錢', pinyin: 'zhǎo qián', english: 'Change (money)'),
    ],
  ),
  PhraseCategory(
    id: 'transport',
    iconPath: AppIcons.bus,
    nameZh: '交通出行',
    nameEn: 'Transport',
    phrases: [
      DailyPhrase(chinese: '地鐵', pinyin: 'dì tiě', english: 'Subway'),
      DailyPhrase(chinese: '公交車', pinyin: 'gōng jiāo chē', english: 'Bus'),
      DailyPhrase(chinese: '紅綠燈', pinyin: 'hóng lǜ dēng', english: 'Traffic light'),
      DailyPhrase(chinese: '斑馬線', pinyin: 'bān mǎ xiàn', english: 'Crosswalk'),
      DailyPhrase(chinese: '出租車', pinyin: 'chū zū chē', english: 'Taxi'),
      DailyPhrase(chinese: '火車站', pinyin: 'huǒ chē zhàn', english: 'Train station'),
      DailyPhrase(chinese: '飛機場', pinyin: 'fēi jī chǎng', english: 'Airport'),
      DailyPhrase(chinese: '停車場', pinyin: 'tíng chē chǎng', english: 'Parking lot'),
    ],
  ),
  PhraseCategory(
    id: 'hospital',
    iconPath: AppIcons.hospital,
    nameZh: '看病就醫',
    nameEn: 'Hospital',
    phrases: [
      DailyPhrase(chinese: '掛號', pinyin: 'guà hào', english: 'Register'),
      DailyPhrase(chinese: '體溫', pinyin: 'tǐ wēn', english: 'Temperature'),
      DailyPhrase(chinese: '藥房', pinyin: 'yào fáng', english: 'Pharmacy'),
      DailyPhrase(chinese: '醫生', pinyin: 'yī shēng', english: 'Doctor'),
      DailyPhrase(chinese: '感冒', pinyin: 'gǎn mào', english: 'Cold (illness)'),
      DailyPhrase(chinese: '頭疼', pinyin: 'tóu téng', english: 'Headache'),
      DailyPhrase(chinese: '吃藥', pinyin: 'chī yào', english: 'Take medicine'),
      DailyPhrase(chinese: '護士', pinyin: 'hù shi', english: 'Nurse'),
    ],
  ),
  PhraseCategory(
    id: 'home_life',
    iconPath: AppIcons.house,
    nameZh: '家庭日常',
    nameEn: 'Home Life',
    phrases: [
      DailyPhrase(chinese: '洗碗', pinyin: 'xǐ wǎn', english: 'Wash dishes'),
      DailyPhrase(chinese: '吸塵器', pinyin: 'xī chén qì', english: 'Vacuum cleaner'),
      DailyPhrase(chinese: '遙控器', pinyin: 'yáo kòng qì', english: 'Remote control'),
      DailyPhrase(chinese: '衣櫃', pinyin: 'yī guì', english: 'Wardrobe'),
      DailyPhrase(chinese: '洗衣機', pinyin: 'xǐ yī jī', english: 'Washing machine'),
      DailyPhrase(chinese: '冰箱', pinyin: 'bīng xiāng', english: 'Fridge'),
      DailyPhrase(chinese: '沙發', pinyin: 'shā fā', english: 'Sofa'),
      DailyPhrase(chinese: '窗戶', pinyin: 'chuāng hu', english: 'Window'),
    ],
  ),
  PhraseCategory(
    id: 'weather',
    iconPath: AppIcons.weather,
    nameZh: '天氣與自然',
    nameEn: 'Weather',
    phrases: [
      DailyPhrase(chinese: '暴風雨', pinyin: 'bào fēng yǔ', english: 'Storm'),
      DailyPhrase(chinese: '彩虹', pinyin: 'cǎi hóng', english: 'Rainbow'),
      DailyPhrase(chinese: '溫度', pinyin: 'wēn dù', english: 'Temperature'),
      DailyPhrase(chinese: '霧霾', pinyin: 'wù mái', english: 'Smog'),
      DailyPhrase(chinese: '下雨', pinyin: 'xià yǔ', english: 'Raining'),
      DailyPhrase(chinese: '颳風', pinyin: 'guā fēng', english: 'Windy'),
      DailyPhrase(chinese: '晴天', pinyin: 'qíng tiān', english: 'Sunny day'),
      DailyPhrase(chinese: '下雪', pinyin: 'xià xuě', english: 'Snowing'),
    ],
  ),
];
