import '../models/daily_phrase.dart';
import '../utils/app_icons.dart';

const String _v = 'assets/images/vocab';

/// Built-in phrase packs inspired by MandaLearn's theme system.
const List<PhraseCategory> kPhraseCategories = [
  PhraseCategory(
    id: 'greetings',
    iconPath: AppIcons.wave,
    nameZh: '打招呼',
    nameEn: 'Greetings',
    phrases: [
      DailyPhrase(chinese: '你好', pinyin: 'nǐ hǎo', english: 'Hello', imagePath: '$_v/hello.png'),
      DailyPhrase(chinese: '早上好', pinyin: 'zǎo shang hǎo', english: 'Good morning', imagePath: '$_v/good_morning.png'),
      DailyPhrase(chinese: '晚上好', pinyin: 'wǎn shang hǎo', english: 'Good evening', imagePath: '$_v/good_evening.png'),
      DailyPhrase(chinese: '再見', pinyin: 'zài jiàn', english: 'Goodbye', imagePath: '$_v/goodbye.png'),
      DailyPhrase(chinese: '謝謝', pinyin: 'xiè xie', english: 'Thank you', imagePath: '$_v/thank_you.png'),
      DailyPhrase(chinese: '不客氣', pinyin: 'bú kè qi', english: "You're welcome", imagePath: '$_v/welcome.png'),
      DailyPhrase(chinese: '對不起', pinyin: 'duì bu qǐ', english: 'Sorry', imagePath: '$_v/sorry.png'),
      DailyPhrase(chinese: '沒關係', pinyin: 'méi guān xi', english: "It's okay", imagePath: '$_v/its_okay.png'),
    ],
  ),
  PhraseCategory(
    id: 'restaurant',
    iconPath: AppIcons.burger,
    nameZh: '餐廳與美食',
    nameEn: 'Restaurant',
    phrases: [
      DailyPhrase(chinese: '筷子', pinyin: 'kuài zi', english: 'Chopsticks', imagePath: '$_v/chopsticks.png'),
      DailyPhrase(chinese: '點菜', pinyin: 'diǎn cài', english: 'Order food', imagePath: '$_v/order_food.png'),
      DailyPhrase(chinese: '買單', pinyin: 'mǎi dān', english: 'Pay the bill', imagePath: '$_v/pay_bill.png'),
      DailyPhrase(chinese: '服務員', pinyin: 'fú wù yuán', english: 'Waiter', imagePath: '$_v/waiter.png'),
      DailyPhrase(chinese: '菜單', pinyin: 'cài dān', english: 'Menu', imagePath: '$_v/menu.png'),
      DailyPhrase(chinese: '好吃', pinyin: 'hǎo chī', english: 'Delicious', imagePath: '$_v/delicious.png'),
      DailyPhrase(chinese: '米飯', pinyin: 'mǐ fàn', english: 'Rice', imagePath: '$_v/rice.png'),
      DailyPhrase(chinese: '飲料', pinyin: 'yǐn liào', english: 'Drink', imagePath: '$_v/drink.png'),
    ],
  ),
  PhraseCategory(
    id: 'school',
    iconPath: AppIcons.school,
    nameZh: '校園生活',
    nameEn: 'School Life',
    phrases: [
      DailyPhrase(chinese: '課本', pinyin: 'kè běn', english: 'Textbook', imagePath: '$_v/textbook.png'),
      DailyPhrase(chinese: '操場', pinyin: 'cāo chǎng', english: 'Playground', imagePath: '$_v/playground.png'),
      DailyPhrase(chinese: '考試', pinyin: 'kǎo shì', english: 'Exam', imagePath: '$_v/exam.png'),
      DailyPhrase(chinese: '同學', pinyin: 'tóng xué', english: 'Classmate', imagePath: '$_v/classmate.png'),
      DailyPhrase(chinese: '老師', pinyin: 'lǎo shī', english: 'Teacher', imagePath: '$_v/teacher.png'),
      DailyPhrase(chinese: '作業', pinyin: 'zuò yè', english: 'Homework', imagePath: '$_v/homework.png'),
      DailyPhrase(chinese: '教室', pinyin: 'jiào shì', english: 'Classroom', imagePath: '$_v/classroom.png'),
      DailyPhrase(chinese: '圖書館', pinyin: 'tú shū guǎn', english: 'Library', imagePath: '$_v/library.png'),
    ],
  ),
  PhraseCategory(
    id: 'shopping',
    iconPath: AppIcons.cart,
    nameZh: '超市購物',
    nameEn: 'Shopping',
    phrases: [
      DailyPhrase(chinese: '收銀台', pinyin: 'shōu yín tái', english: 'Cashier', imagePath: '$_v/cashier.png'),
      DailyPhrase(chinese: '打折', pinyin: 'dǎ zhé', english: 'Discount', imagePath: '$_v/discount.png'),
      DailyPhrase(chinese: '購物車', pinyin: 'gòu wù chē', english: 'Shopping cart', imagePath: '$_v/shopping_cart.png'),
      DailyPhrase(chinese: '零食', pinyin: 'líng shí', english: 'Snacks', imagePath: '$_v/snacks.png'),
      DailyPhrase(chinese: '多少錢', pinyin: 'duō shao qián', english: 'How much?', imagePath: '$_v/how_much.png'),
      DailyPhrase(chinese: '太貴了', pinyin: 'tài guì le', english: 'Too expensive', imagePath: '$_v/expensive.png'),
      DailyPhrase(chinese: '便宜', pinyin: 'pián yi', english: 'Cheap', imagePath: '$_v/cheap.png'),
      DailyPhrase(chinese: '找錢', pinyin: 'zhǎo qián', english: 'Change (money)', imagePath: '$_v/change_money.png'),
    ],
  ),
  PhraseCategory(
    id: 'transport',
    iconPath: AppIcons.bus,
    nameZh: '交通出行',
    nameEn: 'Transport',
    phrases: [
      DailyPhrase(chinese: '地鐵', pinyin: 'dì tiě', english: 'Subway', imagePath: '$_v/subway.png'),
      DailyPhrase(chinese: '公交車', pinyin: 'gōng jiāo chē', english: 'Bus', imagePath: '$_v/bus_transport.png'),
      DailyPhrase(chinese: '紅綠燈', pinyin: 'hóng lǜ dēng', english: 'Traffic light', imagePath: '$_v/traffic_light.png'),
      DailyPhrase(chinese: '斑馬線', pinyin: 'bān mǎ xiàn', english: 'Crosswalk', imagePath: '$_v/crosswalk.png'),
      DailyPhrase(chinese: '出租車', pinyin: 'chū zū chē', english: 'Taxi', imagePath: '$_v/taxi.png'),
      DailyPhrase(chinese: '火車站', pinyin: 'huǒ chē zhàn', english: 'Train station', imagePath: '$_v/train_station.png'),
      DailyPhrase(chinese: '飛機場', pinyin: 'fēi jī chǎng', english: 'Airport', imagePath: '$_v/airport.png'),
      DailyPhrase(chinese: '停車場', pinyin: 'tíng chē chǎng', english: 'Parking lot', imagePath: '$_v/parking.png'),
    ],
  ),
  PhraseCategory(
    id: 'hospital',
    iconPath: AppIcons.hospital,
    nameZh: '看病就醫',
    nameEn: 'Hospital',
    phrases: [
      DailyPhrase(chinese: '掛號', pinyin: 'guà hào', english: 'Register', imagePath: '$_v/register_hospital.png'),
      DailyPhrase(chinese: '體溫', pinyin: 'tǐ wēn', english: 'Temperature', imagePath: '$_v/body_temp.png'),
      DailyPhrase(chinese: '藥房', pinyin: 'yào fáng', english: 'Pharmacy', imagePath: '$_v/pharmacy.png'),
      DailyPhrase(chinese: '醫生', pinyin: 'yī shēng', english: 'Doctor', imagePath: '$_v/doctor.png'),
      DailyPhrase(chinese: '感冒', pinyin: 'gǎn mào', english: 'Cold (illness)', imagePath: '$_v/cold_illness.png'),
      DailyPhrase(chinese: '頭疼', pinyin: 'tóu téng', english: 'Headache', imagePath: '$_v/headache.png'),
      DailyPhrase(chinese: '吃藥', pinyin: 'chī yào', english: 'Take medicine', imagePath: '$_v/take_medicine.png'),
      DailyPhrase(chinese: '護士', pinyin: 'hù shi', english: 'Nurse', imagePath: '$_v/nurse.png'),
    ],
  ),
  PhraseCategory(
    id: 'home_life',
    iconPath: AppIcons.house,
    nameZh: '家庭日常',
    nameEn: 'Home Life',
    phrases: [
      DailyPhrase(chinese: '洗碗', pinyin: 'xǐ wǎn', english: 'Wash dishes', imagePath: '$_v/wash_dishes.png'),
      DailyPhrase(chinese: '吸塵器', pinyin: 'xī chén qì', english: 'Vacuum cleaner', imagePath: '$_v/vacuum.png'),
      DailyPhrase(chinese: '遙控器', pinyin: 'yáo kòng qì', english: 'Remote control', imagePath: '$_v/remote.png'),
      DailyPhrase(chinese: '衣櫃', pinyin: 'yī guì', english: 'Wardrobe', imagePath: '$_v/wardrobe.png'),
      DailyPhrase(chinese: '洗衣機', pinyin: 'xǐ yī jī', english: 'Washing machine', imagePath: '$_v/washing_machine.png'),
      DailyPhrase(chinese: '冰箱', pinyin: 'bīng xiāng', english: 'Fridge', imagePath: '$_v/fridge.png'),
      DailyPhrase(chinese: '沙發', pinyin: 'shā fā', english: 'Sofa', imagePath: '$_v/sofa.png'),
      DailyPhrase(chinese: '窗戶', pinyin: 'chuāng hu', english: 'Window', imagePath: '$_v/window.png'),
    ],
  ),
  PhraseCategory(
    id: 'weather',
    iconPath: AppIcons.weather,
    nameZh: '天氣與自然',
    nameEn: 'Weather',
    phrases: [
      DailyPhrase(chinese: '暴風雨', pinyin: 'bào fēng yǔ', english: 'Storm', imagePath: '$_v/storm.png'),
      DailyPhrase(chinese: '彩虹', pinyin: 'cǎi hóng', english: 'Rainbow', imagePath: '$_v/rainbow.png'),
      DailyPhrase(chinese: '溫度', pinyin: 'wēn dù', english: 'Temperature', imagePath: '$_v/thermometer.png'),
      DailyPhrase(chinese: '霧霾', pinyin: 'wù mái', english: 'Smog', imagePath: '$_v/smog.png'),
      DailyPhrase(chinese: '下雨', pinyin: 'xià yǔ', english: 'Raining', imagePath: '$_v/raining.png'),
      DailyPhrase(chinese: '颳風', pinyin: 'guā fēng', english: 'Windy', imagePath: '$_v/windy.png'),
      DailyPhrase(chinese: '晴天', pinyin: 'qíng tiān', english: 'Sunny day', imagePath: '$_v/sunny.png'),
      DailyPhrase(chinese: '下雪', pinyin: 'xià xuě', english: 'Snowing', imagePath: '$_v/snowing.png'),
    ],
  ),
];
